from pathlib import Path
import json
out=[]
def add(a,l,t,q,p,s,*urls): out.append(dict(article=a,line=l,type=t,quote=q,problem=p,suggestion=s,sources=list(urls)))
U='https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-3/'
B='https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html'
C='https://www.man7.org/linux/man-pages/man5/crontab.5.html'
S='https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html'
T='https://man7.org/linux/man-pages/man1/top.1.html'
add(52,141,'事实错误','M 和 E 分别是实际存储的 exp 和 frac','尾数和指数的对应关系写反。','改为：E 对应 exp 字段，M 的有效数字部分对应 frac 字段（并说明正规数的隐含首位）。','https://docs.oracle.com/cd/E19957-01/806-3568/ncg_math.html')
add(54,60,'事实错误','手动调整原子钟，使得误差不至于超过一秒','闰秒调整的是 UTC 与 TAI 的整数秒差，不是让原子钟改变走速。约束的是 UT1 与 UTC。','改为：通过在 UTC 中引入闰秒，使 |UT1−UTC| 小于 0.9 秒；TAI 连续计时。','https://www.iers.org/SharedDocs/Publikationen/EN/IERS/Documents/IERS_Leap_Seconds.pdf?__blob=publicationFile&v=1')
add(54,94,'适用条件','2038 年问题','该问题针对以有符号 32 位整数计秒的时间表示，不能泛化到所有计算机。','明确 time_t/存储格式的位宽；64 位时间表示不受这个同一边界限制。','https://man7.org/linux/man-pages/man3/time.3type.html')
add(54,134,'字词错误','预兆公历；ISO_lOCAL_DATE；地球自传','术语及字母大小写错误（另见 L56、L279）。','分别改为“前推公历”“ISO_LOCAL_DATE”“地球自转”。')
add(55,94,'事实错误','Unicode 没有规定这些字节该如何存储','Unicode 标准包含 UTF-8、UTF-16、UTF-32 的编码定义。','改为：码点是抽象编号；具体字节表示由 UTF 编码形式和编码方案确定。',U)
add(55,126,'事实错误','0x00000000 到 0x7FFFFFFF','把历史 UCS-4 的 31 位空间误当成现代 UTF-32 的有效值。','UTF-32 编码 Unicode 标量值：U+0000～U+10FFFF，排除 U+D800～U+DFFF；同步修改 L132。',U)
add(55,206,'适用条件','BMP 中的字符','BMP 包含代理码点，不能全部当成可单独编码的字符。','单个 UTF-16 码元对应 BMP 中除代理区以外的标量值；L280 的 UTF-8 BMP 说明也排除代理区。',U)
add(55,290,'事实错误','110xxxxx；11110xxx','合法 UTF-8 首字节范围不是 C0～DF、F0～F7；必须排除过长编码、代理值、超过 U+10FFFF 的编码。','首字节范围改为 C2～DF、E0～EF、F0～F4，并补充 E0/ED/F0/F4 对第二字节的限制。','https://www.rfc-editor.org/rfc/rfc3629.html')
add(55,345,'字词错误','UTF-16；不在；小段','对应小节讲 UTF-8；另有“不再”“小端”的错字（L373、L383）。','标题改为 UTF-8；“不在”改“不再”；“小段”改“小端”。')
add(56,21,'概念混淆','渲染帧','程序渲染帧率 FPS 与显示器刷新率 Hz 不等同。','区分帧率与刷新率，并说明垂直同步、丢帧及重复显示的情况。','https://docs.unity3d.com/Manual/TimeFrameManagement.html')
add(56,61,'适用条件','State2','两个已知状态之间的插值需要已经计算出后一状态；当前时间领先于最新逻辑状态时不能直接获得未来状态。','明确插值采用一逻辑步的显示延迟；若预测未来状态，应称外推并说明误差。','https://docs.unity3d.com/Manual/TimeFrameManagement.html')
add(58,52,'字词错误','setttings','单词多写了一个 t。','改为 settings。')
add(59,222,'字词错误','GitHub Page','产品名称应为 GitHub Pages。','改为 GitHub Pages。')
add(60,93,'适用条件','重启','--permanent 修改持久配置，单独执行不等于立即修改运行时规则；运行时与持久配置应区分。','需要立即生效时同时修改运行时规则或 reload；重启/重载是否断开 SSH 取决于规则和连接跟踪，不能绝对断言。','https://firewalld.org/documentation/configuration/runtime-versus-permanent.html')
add(61,47,'事实错误','?、L、W、#','把 Quartz Cron 与 Linux crontab 混在同一语法表中。','Linux 用户 crontab 使用五个时间字段；?, L, W, # 不是常规 Cronie 语法，移到单独的 Quartz 小节并标明六/七字段和不同星期编号。',C,'https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html')
add(61,86,'命令错误','0 0 0 1 1 ?','六字段示例不能直接放进 Linux crontab。','四条示例依次改为：0 0 1 1 *；59 6 15 5 *；30 15 * 9 0；30 19 * 12 6，并加实际命令字段。',C)
add(61,111,'命令错误','crontab -u','-u 指定用户，不是编辑操作本身；-i 通常配合删除确认。','编辑写 crontab -u 用户名 -e（需相应权限）；交互删除写 crontab -i -r。','https://man7.org/linux/man-pages/man1/crontab.1.html')
add(62,61,'命令错误','PATH="$PATH:$JAVA_HOME/bin"','追加到 PATH 后部会继续优先匹配旧 Java，不能保证切换至 JDK21。','改为 PATH="$JAVA_HOME/bin:$PATH"，或使用 update-alternatives；用 command -v java、java -version 验证。','https://www.gnu.org/software/bash/manual/html_node/Command-Search-and-Execution.html')
add(63,68,'字词错误','aux','MongoDB CPU 要求中的指令集拼错。','改为 AVX；MongoDB 5.0 及以后 x86_64 的硬件要求按官方文档列明。','https://www.mongodb.com/docs/v7.0/administration/production-notes/')
add(65,34,'事实错误','Loki','Loki 属于 Grafana 生态的日志系统，并非 Prometheus 项目的日志组件。','改为：Prometheus 负责指标；Grafana Loki 负责日志，Grafana 可查询两者。','https://grafana.com/docs/loki/latest/get-started/overview/')
add(67,137,'事实错误','SHA512','SHA-512 并不一定比 SHA-256 慢，尤其在 64 位平台上。','删去无条件快慢判断；校验算法按发行方提供的摘要选择，不以算法位数推断运行速度。','https://www.openssl.org/docs/man3.0/man1/openssl-speed.html')
add(67,287,'适用条件','sudo','Debian 安装时是否创建 root 密码影响 sudo 的默认安装和首个用户授权。','明确：未设置 root 密码时通常安装 sudo 并授权首个用户；已设置 root 密码时，可能需要 su 后手动安装配置。','https://wiki.debian.org/sudo')
add(67,331,'版本条件','netselect-apt -sn','不指定发行版默认跟随 stable，会在 stable 变更后生成其他发行版的源；-n 表示包含 non-free。','Debian12 教程显式指定 bookworm，例如 netselect-apt -s -n bookworm，并核对生成的 sources.list。','https://manpages.debian.org/trixie/netselect-apt/netselect-apt.1.en.html')
add(67,422,'适用条件','ping','ping 无响应不证明地址无人使用，设备可能离线或禁用 ICMP。','静态地址应在 DHCP 池外并由网络管理者保留；可辅助做 ARP 冲突探测，但不把扫描结果当成永久无冲突保证。','https://www.rfc-editor.org/rfc/rfc5227.html')
add(68,86,'事实错误','默认','du 默认报告目录累计大小，不逐个列出普通文件。','逐个显示文件需 du -a；只要目录汇总用默认选项，单个总计可用 du -s。','https://www.gnu.org/software/coreutils/manual/html_node/du-invocation.html')
add(68,94,'字词错误','文档系统','名词写错。','改为文件系统。')
add(71,15,'事实错误','与互联网隔绝','内网地址不等于没有互联网连接；frpc 通常依赖能主动连接公网 frps。','改为：位于 NAT/防火墙后，公网无法直接发起到该主机的连接，但主机可向公网建立出站连接。','https://gofrp.org/en/docs/overview/')
add(72,98,'字词错误','/user/bin；-empy','目录和 find 选项拼错（另见 L154）。','改为 /usr/bin 和 -empty。','https://www.gnu.org/software/findutils/manual/html_mono/find.html')
add(72,211,'适用条件','一次','find -exec … + 会在命令行长度限制内分批执行，不保证所有结果只调用一次。','改为：尽量将多个结果合并为一批，必要时执行多批。','https://www.gnu.org/software/findutils/manual/html_node/find_html/Multiple-Files.html')
add(73,105,'字词错误','198.168','前后示例是 192.168 私网网段，此处地址误写。','改为与示例一致的 192.168，并修正语法框中的缺失右括号。')
add(74,45,'链接错误','http://127','Markdown 链接目标包含了中文正文，无法按意图打开。','将中文解释移到链接括号外；目标只保留代理 URL。')
add(75,37,'字词错误','列','-A/-B/-C 展示的是上下文行，不是列。','改为“行”，示例补足数量参数，例如 grep -A 3 pattern file。','https://www.gnu.org/software/grep/manual/grep.html')
add(76,29,'事实错误','LC_COLLATE=en_US.UTF-8','en_US.UTF-8 的排序由语言环境规则决定，不等于 ASCII 字节顺序。','需要可复现的字节顺序时使用 LC_ALL=C sort …；区分字符编码与排序规则。','https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html')
add(76,127,'代码错误','sorted(...).thenComparing','Stream 没有 thenComparing 方法，该方法属于 Comparator。','写成 stream.sorted(Comparator.comparing(...).thenComparing(...))。','https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Comparator.html')
add(77,220,'事实错误','执行顺序','登录 Bash 首先读取 /etc/profile，再读取首个存在的 ~/.bash_profile、~/.bash_login、~/.profile；bashrc 是否被读取依赖这些文件显式 source。','重写顺序图；交互非登录 Bash 读取 ~/.bashrc，/etc/bashrc 是否参与取决于发行版配置。',B)
add(77,333,'事实错误','u符号代表当前用户','chmod 的 u/g 指文件属主/文件属组，与执行 chmod 的当前用户/当前用户组不是同一概念。','u=文件所有者；g=文件所属组；o=其余用户；sticky bit 删除限制还包括有特权的进程。','https://www.gnu.org/software/coreutils/manual/html_node/Setting-Permissions.html')
add(77,131,'适用条件','不然没法使用这个账号登录','锁定密码不等于任何认证方式都无法登录；SSH 公钥登录还受 sshd、PAM、账号状态影响。','改为：要使用密码认证需设置密码；公钥等其他认证另行配置。','https://man7.org/linux/man-pages/man8/useradd.8.html')
add(77,485,'命令/字词错误','gpassed','命令应为 gpasswd。另有“200 原”“第中间”“baserc”“pubic”等拼写（L47/L55/L234/L315/L369）。','改为 gpasswd；分别改成“中间”“200 元”“bashrc”“public”；.bash_history 补前导点（L208）。')
add(78,23,'事实错误','镜像副本','硬链接是同一 inode 的另一目录项，不复制数据。','改为：两个名字引用同一文件，修改任一名字所指内容会反映到另一个名字。','https://man7.org/linux/man-pages/man2/link.2.html')
add(78,85,'事实错误','512 字节并不是全部存储数据','向系统暴露的 512 字节逻辑扇区是数据负载；同步、头标、ECC 等物理编码开销在额外空间中。','区分逻辑扇区的数据容量与介质上的物理格式开销。','https://www.seagate.com/files/staticfiles/docs/pdf/whitepaper/tp613_4k_transition.pdf')
add(78,110,'事实错误','8 位；6 位；1023','传统 BIOS CHS 是柱面10位、磁头8位、扇区6位；柱面编号0～1023对应1024个柱面。','交换扇区/磁头位宽；说明常用255磁头的转换约定与字段可表示256的区别，使用1024计算柱面数量。','https://uefi.org/specs/UEFI/2.10/13_Protocols_Media_Access.html')
add(78,143,'事实错误','一个文件，至少要占用一个数据块','空文件可不占数据块；稀疏文件和 inline data 等也使这条绝对说法不成立；stat 的 IO Block 不是已分配块大小的充分证据。','改为：常见非空、非内联普通文件按文件系统分配单位分配空间；区分 st_blksize、st_blocks、文件系统块大小。','https://man7.org/linux/man-pages/man7/inode.7.html','https://docs.kernel.org/filesystems/ext4/ifork.html')
add(78,245,'适用条件','减少为 0…回收','最后一个硬链接被删后，仍被进程打开的文件不会立即释放。','加上：链接计数为零且最后一个打开引用释放后，才回收资源。','https://man7.org/linux/man-pages/man2/unlink.2.html')
add(78,214,'字词错误','真是文件；books.tx；book.txt','“真实”误写，示例文件名不一致（另见 L46/L175/L183）。','改为“真实文件”，文件名统一 books.txt。')
add(79,58,'配置错误','base-url: "notify.test.com"','base-url 需要包含协议的外部访问 URL。','当前 HTTP 代理例改为 http://notify.test.com；HTTPS 部署则使用相应 https URL。','https://docs.ntfy.sh/config/')
add(81,39,'路径错误','~/.SSH/config','Linux 路径区分大小写；OpenSSH 默认读取 ~/.ssh/config。','改为 ~/.ssh/config。','https://man.openbsd.org/ssh_config')
add(82,61,'事实错误','客户端尝试了太多认证方式','Connection closed … [preauth] 只说明认证前连接关闭，不能据此确定超过认证次数。','明确仅凭该行无法判断原因；超过次数通常有 Too many authentication failures 或 maximum authentication attempts exceeded 等记录。','https://github.com/openssh/openssh-portable/blob/master/auth.c')
add(82,50,'字词错误','时间辍','错字。','改为时间戳。')
add(83,72,'事实错误','如果高，CPU 可能会过度工作','id 是空闲时间比例，解释方向反了。','改为：id 越高通常越空闲，越低说明 CPU 忙；ni 是运行被调整 nice 值的进程所消耗的用户态 CPU 时间，不是“好值”。',T)
add(83,61,'事实错误','僵尸进程通常意味着…没有正常退出','僵尸进程已经终止，只是退出状态尚未被父进程 wait 回收；正常退出也可产生。','改为：已退出但未被回收的进程；孤儿是父进程先退出的另一概念。','https://man7.org/linux/man-pages/man2/wait.2.html')
add(83,92,'概念混淆','free：可用…Swap…虚拟内存','free 是完全空闲物理内存，available 是可供新程序使用且不必交换的估计量；Swap 只是虚拟内存机制的一部分。','区分 free/available、交换空间/整个虚拟内存；不能由 Swap 非零直接推断 RAM 不足。',T)
add(85,29,'字词错误','Loca','应为 Local（时钟误差的推断另需与截图及参考时钟核对）。','改为 Local。')
add(88,16,'字词/链接错误','mimproxy；自动成；链接','工具名改 mitmproxy；L54“自动成”改“自动生成”；L50“专用链接”改“专用连接”；L42 链接目标删中文。','链接目标只保留 http://example.com/，解释放在括号外。')
add(90,59,'适用条件','umount 是需要 sudo 权限的','umount 在 fstab user/users 等授权条件下可由普通用户调用。','改为：普通挂载通常需要特权；fstab 授权或 udisks/Polkit 可允许普通用户卸载；L71“关闭闭”改“关闭”。','https://man7.org/linux/man-pages/man8/umount.8.html')
add(91,78,'事实/拼写错误','用户名和密码都是：Ubuntu','该镜像默认凭据为小写 ubuntu，大小写会影响登录。','改为 ubuntu/ubuntu；L44“准本”改“准备”；L156 写 Ubuntu22.04=jammy，而非所有22.x。','https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi')
add(94,18,'事实错误','两者的不同…CentOS 完全开源','RHEL 本身也由开源软件构成，不能把两者差异概括成一方开源、一方不开放。','写清商业订阅、支持和发行方式的差别。','https://www.redhat.com/en/about/open-source')
add(94,245,'事实错误','yum…需要联网','yum 可以使用本地目录或挂载介质仓库，并非必然需要互联网。','改为：使用远程仓库时需要网络；离线环境可建立本地 yum 仓库并解析依赖。','https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-configuring_yum_and_yum_repositories')
add(94,434,'命令风险','rpm -e --nodeps mariadb-libs','跳过依赖检查会留下破损依赖；MySQL 官方提供兼容库以支持迁移。','按 MySQL5.7 官方 RPM 替换流程处理 mariadb-libs，保留/安装 mysql-community-libs-compat 并检查 postfix 等依赖。','https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/')
add(94,577,'字词错误','/usr/loacl/redis/；Vitual Box；NetworkManger；变软','路径和名称拼写错误；L815 把 Nginx 启动写成 redisd。','改 /usr/local/redis/、VirtualBox、NetworkManager、“编译”；L750补“不用”；L815改 nginxd。')
add(59,18,'版本时效','CentOS7','该历史环境教程可以保留，但 CentOS7 已结束支持，当前下载源路径和新部署建议需注明。','在本篇及 ID60、94 的 CentOS7 内容加历史版本说明；旧镜像按 CentOS Vault 归档获取。','https://www.centos.org/centos-linux-eol/')
add(95,137,'事实错误','主服务进程执行完成之后','Type=exec 等待成功 execve 启动程序，不等程序退出；该句与后面的解释矛盾。','改为“主服务进程的可执行程序成功启动之后”。',S)
add(95,141,'版本条件','notify 尚不能与 PrivateNetwork=yes 一起使用','这是旧版本限制，不宜沿用到本文2025年环境。','按所用 systemd 版本说明；现代通知使用文件系统命名的 Unix socket，不再保留这条普遍禁用结论。',S)
add(95,240,'适用条件','always: 无条件重启','systemctl stop/restart 等由 systemd 主动结束进程时不会触发该自动重启条件；StartLimitBurst 统计启动次数不只是失败次数。','改为：进程正常/异常退出都会自动重启，但有管理操作与启动限流等例外；60秒最多3次启动包括首次启动。',S)
add(95,75,'字词错误','WangtedBy','配置项拼写错误。','改为 WantedBy。')
add(96,292,'命令错误','SSH…-p 表示端口','ssh -p 是端口，但 ssh-keygen/scp/sftp 参数各不同；本句大体正确，无需将工具混同。','保留 ssh/scp 对照，并补充说明选项不是跨工具统一规范。')
out.pop() # 不把正确的 ssh/scp 对照列为错误
add(96,199,'字词错误','用用','重复字；L20“图像的的”及其他明显重复按原文核对。','改为“用”。')
add(97,54,'事实错误','Socket(s)…即物理核心数','插槽/CPU 封装数不等于核心数。','Socket(s) 是 CPU 插槽/封装数；每封装可含多个核心和多个逻辑线程。','https://man7.org/linux/man-pages/man1/lscpu.1.html')
add(97,212,'事实错误','生成 10000 个素数','cpu-max-prime=10000 是素数测试的整数上限，不是生成10000个素数。','改为：每个 CPU 测试事件计算/检查直到该上限的素数；比较 events/s 时固定上限、线程数与时间。','https://github.com/akopytov/sysbench/blob/master/src/tests/cpu/sb_cpu.c')
add(97,153,'字词错误','如果您想 df','该段解释 du，应为 du；L20“如果”应为“如何”。','同步修正这两个词。')
add(98,71,'事实错误','很动态…安全性相对较高','环境是进程启动时继承的副本；修改父 shell 不会更新已运行的子进程。环境还可能被调试接口/日志等读取，不能天然保证密钥安全。','改为：便于启动时注入配置，不自动支持运行时更新；密钥保护仍依赖权限、日志处理和部署方式。','https://man7.org/linux/man-pages/man7/environ.7.html')
add(98,38,'适用/字词错误','子进程也无法访问 shell 变量','exec 启动程序不会自动继承未 export 的变量，但 fork 出的 subshell（如括号子 shell）会继承 shell 状态。另有“推出”“改变量”。','限定为执行独立程序的环境继承；改“退出”“该变量”（L124/L137）。','https://www.gnu.org/software/bash/manual/html_node/Command-Execution-Environment.html')
add(99,28,'适用条件','busybox rpm -ivh','BusyBox 的 rpm applet 不实现完整 RPM 安装语义，安装脚本/依赖处理能力不能等同系统 rpm；静态编译且包含该 applet 是前提。','保留实际恢复经历，但标注准确二进制及 applet 支持、包文件路径；说明应进一步用恢复的系统 rpm 检查包状态，不泛化为通用完整安装。','https://busybox.net/downloads/BusyBox.html')
add(99,73,'代码错误','OutputStream outputStream','每轮新建输出流后未关闭。','每次循环用 try-with-resources 包住 Files.newOutputStream；L47“有仅有”改“仅有”。','https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/OutputStream.html')
Path(__file__).with_name('findings-03.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(out))
